function dataM = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  CUSTOMDATA20201124RECORDING5 = IMPORTFILE(FILENAME) reads data from
%  text file FILENAME for the default selection.  Returns the numeric
%  data.
%
%  CUSTOMDATA20201124RECORDING5 = IMPORTFILE(FILE, DATALINES) reads data
%  for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  CustomData20201124Recording5 = importfile("C:\Users\j3lac\OneDrive\Documenten\BEP\CSV Arduino recordings\Setup test\Custom Data - 2020-11-24 - Recording 5.csv", [4, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 24-Nov-2020 15:46:56

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [4, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 36);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["VarName1", "Workbook", "Custom", "Custom_1", "VarName5", "VarName6", "VarName7", "VarName8", "VarName9", "VarName10", "VarName11", "VarName12", "VarName13", "VarName14", "VarName15", "VarName16", "VarName17", "VarName18", "VarName19", "VarName20", "VarName21", "VarName22", "VarName23", "VarName24", "VarName25", "VarName26", "VarName27", "VarName28", "VarName29", "VarName30", "VarName31", "VarName32", "VarName33", "VarName34", "VarName35", "VarName36"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["VarName1", "Workbook", "Custom", "Custom_1", "VarName5", "VarName6", "VarName7", "VarName8", "VarName9", "VarName10", "VarName11", "VarName12", "VarName13", "VarName14", "VarName15", "VarName16", "VarName17", "VarName18", "VarName19", "VarName20", "VarName21", "VarName22", "VarName23", "VarName24", "VarName25", "VarName26", "VarName27", "VarName28", "VarName29", "VarName30", "VarName31", "VarName32", "VarName33", "VarName34", "VarName35", "VarName36"], "FillValue", 0);
opts = setvaropts(opts, "VarName36", "TrimNonNumeric", true);
opts = setvaropts(opts, "VarName36", "ThousandsSeparator", ",");

% Import the data
dataM = readtable(filename, opts);

%% Convert to output type
dataM = table2array(dataM);
end